name: rw_low
description: rw_low
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  tuple: ^1.0.2
  path: ^1.6.2
  recase: ^2.0.1
  protobuf: ^0.13.4
  grpc: ^1.0.1
    
dev_dependencies:
  test: '>=0.12.0 <2.0.0'
