name: rw_utils
description: rw_utils
version: 0.0.2

environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  tuple: ^1.0.2
  path: ^1.6.2
  recase: ^2.0.1
  json_annotation: ^2.0.0
  collection:
  protobuf: ^0.13.4
  crypto:
  grpc: ^1.0.1 
  pool: ^1.4.0
  intl: ^0.15.8
  cooky: ^1.0.1 
  shelf: ^0.7.5
  shelf_static: ^0.2.8
  shelf_router: ^0.7.0+1
  # shelf_web_socket: # dart
  # shelf_proxy:
  # shelf_gzip:
  rw_low: 
    path: ../../rw_low
    
dev_dependencies:
  test: '>=0.12.0 <2.0.0'
  json_serializable: '>=2.0.1'
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^1.0.0
  github: ^4.1.0

