name: rewise_model
description: 
version: 1.0.0

environment:
  sdk: '>=2.4.0 <3.0.0'
  flutter: '>=1.8.2-pre.211'

dependencies:
  flutter: 
    sdk: flutter

  cupertino_icons: ^0.1.0

  functional_widget_annotation: any
  provider: any

  navigation: any

# builders:
  # functional_widget: ^0.7.1

# flutter packages pub run build_runner watch
# OR
# flutter packages pub run build_runner build
dev_dependencies: 
  build_runner: ^1.0.0
  functional_widget: ^0.7.1

dependency_overrides:
  navigation:
    path: ../navigation/
