name: navigation
description: An example project for flutter-desktop-embedding.
version: 1.0.0

environment:
  sdk: '>=2.4.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.8.2-pre.211'

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^0.1.0

  functional_widget_annotation: any
  provider: any

builders:
  functional_widget: any

flutter:
  uses-material-design: true
